# Generated by Django 4.1.3 on 2022-11-20 13:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('promoted_students', django.db.models.manager.Manager()),
            ],
        ),
    ]
